### PR TITLE
Fixes for Ellesmere

### PR DESCRIPTION
**Pull request by zawawawa**
Add Ellesmere to the AMD OpenCL 1.2. ABI. See: https://community.amd.com/thread/210432

### CODE REVIEW

**Comment by matszpk** [comment]
Thank you for patch. AMD OpenCL 1.2 binary format handling is fixed for Ellesmere. I looked up what a ELF flags code for Ellesmere for newest drivers (2236.09) is: in my generated binaries is: 16 instead 15. Can you tell me what a driver version are you using?

**Comment by matszpk** [comment]
I looked up in your patch. I am guessing that is new AMD GPU-PRO driver.

**Comment by zawawawa** [comment]
Thank you for the update. The driver is Crimson 10.1. I am out of town now, but I will make sure to look up the driver version next week.

**Comment by matszpk** [comment]
By default, drivers >=16.4 build any kernel to AmdCL2 format regardless whether you are specify OpenCL1.2 standard or OpenCL 2.0 for all devices based on GCN >=1.1. How did you build binaries in older format for Ellesmere? Drivers <=16.3 doesn't support Ellesmere.

**Comment by matszpk** [comment]
I added a missing code of GPU device types for AMD OpenCL 1.2 (Baffin, Goose, Horse, Stoney).

**Comment by zawawawa** [comment]
With Crimson drivers, you can build binaries for Ellesmere in the older format by specifying the "-legacy" build option when you call clCreateProgramWithSource(). You could also do the same thing with CodeXL.

**Comment by zawawawa** [comment]
I was actually wrong about the driver, I was using Crimson 16.9.2, and the driver version is "2117.13 (VM)". Hope this helps.

**Pull request closed without merging**
